complete --command=posix-source --description='Source env files'
complete --command=posix-source --short-option=h --long-option=help --description='Print help file'
complete --command=posix-source --short-option=n --long-option=no-interpret --description='Don’t evaluate variables in env files'
complete --command=posix-source --short-option=p --long-option=print --description='Print fish commands to STDOUT instead of setting varaibles'
complete --command=posix-source --short-option=G --long-option=no-global --description='Unset variable at end of block'
complete --command=posix-source --short-option=u --long-option=unexport --description='Don’t export variable to child processes'
complete --command=posix-source --short-option=e --long-option=erase --description='Erase variables listed in file'
