#
# ~/.bashrc
#

[[ $- != *i* ]] && return

# disable interpreting <ctrl+s> as signal for stopping terminal updates
stty -ixon

# Terminal to kitty
source <(kitty + complete setup bash)
export TERMINAL="kitty"

# add keychain
eval $(keychain --eval --quiet --nogui --noask github gitlab)

# alias dartfmt
alias dartfmt="dart format"

# Fish
# drop into fish if parent process is NOT fish
# invoke `bash` from fish with `bash` (sources `~/.bashrc`)
if [[ $(ps -p $PPID -o command | tail -n +2) != "fish" ]]
then
  exec fish
fi

source /home/owlhoot/.config/broot/launcher/bash/br
