#
# ~/.bashrc
#

[[ $- != *i* ]] && return

# disable interpreting <ctrl+s> as signal for stopping terminal updates
stty -ixon

# Terminal to sterminal
export TERMINAL="kitty"

# Fish Shell
exec fish
