#
# ~/.bashrc
#

[[ $- != *i* ]] && return

# disable interpreting <ctrl+s> as signal for stopping terminal updates
stty -ixon

# Terminal to kitty
source <(kitty + complete setup bash)
export TERMINAL="kitty"

# Fish
FISH=$(env PATH="$HOME/local/bin:$HOME/local/bin:$PATH" which fish)

if [[ -x "$FISH" ]]; then
  exec env SHELL="$FISH" "$FISH" -i
fi

if [ -z "$BASH_EXECUTION_STRING" ]; then exec fish; fi
